In [1]:
import pandas as pd
from wordcloud import STOPWORDS

In [2]:
df = pd.read_csv('24-06-2021.csv')
df

Definition  is_misogyny     cleaned_definition
0     Ur gonna die... queer          0.0     ur gonna die queer
1     Valuptuous man boobs.          0.0   valuptuous man boobs
2     Variation of brother.          0.0   variation of brother
3     Very impressive penis          0.0  very impressive penis
4     What I call my penis.          0.0   what i call my penis
...                     ...          ...                    ...
2281  A women who is "easy"          1.0    a women who is easy
2282  Any hot/ sexy chicks.          1.0    any hot sexy chicks
2283  Any vaginal secretion          1.0  any vaginal secretion
2284  Person who slaps hoes          1.0  person who slaps hoes
2285  That hoe out there!!!          1.0     that hoe out there

[2286 rows x 3 columns]

In [3]:
#check what is in STOPWORDS and set the variable stopwords
stopwords = set(STOPWORDS)
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'all',
 'also',
 'am',
 'an',
 'and',
 'any',
 'are',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 "can't",
 'cannot',
 'com',
 'could',
 "couldn't",
 'did',
 "didn't",
 'do',
 'does',
 "doesn't",
 'doing',
 "don't",
 'down',
 'during',
 'each',
 'else',
 'ever',
 'few',
 'for',
 'from',
 'further',
 'get',
 'had',
 "hadn't",
 'has',
 "hasn't",
 'have',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'hence',
 'her',
 'here',
 "here's",
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 "how's",
 'however',
 'http',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'k',
 "let's",
 'like',
 'me',
 'more',
 'most',
 "mustn't",
 'my',
 'myself',
 'no',
 'nor',
 'not',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'otherwise',
 'ought',
 'our',
 

In [4]:
#Create a new column excluding stopwords from cleaned_definition
#For tuple format, it would be .apply(lambda x: [item for item in x.split() if item not in stopwords])

df['cleaned_definition_nostop'] = df['cleaned_definition'].apply(lambda x: ' '.join(
    [item for item in x.split() if item not in stopwords]))

In [5]:
df.head()

Definition  is_misogyny     cleaned_definition  \
0  Ur gonna die... queer          0.0     ur gonna die queer   
1  Valuptuous man boobs.          0.0   valuptuous man boobs   
2  Variation of brother.          0.0   variation of brother   
3  Very impressive penis          0.0  very impressive penis   
4  What I call my penis.          0.0   what i call my penis   

  cleaned_definition_nostop  
0        ur gonna die queer  
1      valuptuous man boobs  
2         variation brother  
3          impressive penis  
4                call penis

In [6]:
#Vectorize column in df using TfidfVectorizer and .fit_transform
#This is to prepare for ML purposes
#Turns text data into binary vector
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
vectorizer = TfidfVectorizer(max_features= 950)
cleaned_definition_vect = vectorizer.fit_transform(df['cleaned_definition_nostop'])


In [8]:
cleaned_definition_vect

<2286x950 sparse matrix of type '<class 'numpy.float64'>'
	with 26787 stored elements in Compressed Sparse Row format>

In [9]:
#converting sparse matrix back to a df and applying column names by .get_feature_names()
from scipy.sparse import csr_matrix

In [10]:
df_vect = pd.DataFrame.sparse.from_spmatrix(cleaned_definition_vect)
df_vect.columns = vectorizer.get_feature_names()

In [11]:
df_vect

10   12   13   14   20   30  ability  able  absolutely  across  ...  \
0     0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
1     0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
2     0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
3     0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
4     0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
...   ...  ...  ...  ...  ...  ...      ...   ...         ...     ...  ...   
2281  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
2282  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
2283  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
2284  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   
2285  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0         0.0     0.0  ...   

      worth  written  wrong  year  years  yes  yet  youll  young  youre  
0       0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
1       0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
2       0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
3       0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
4       0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
...     ...      ...    ...   ...    ...  ...  ...    ...    ...    ...  
2281    0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
2282    0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
2283    0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
2284    0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  
2285    0.0      0.0    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  

[2286 rows x 950 columns]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier 
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import f1_score 
from sklearn.metrics import confusion_matrix 
from sklearn import metrics

In [13]:
#Prepared Independent and Dependent Variables

X = df_vect
y = df.filter(items = ['is_misogyny'])

In [14]:
# Split dataset into 80-20 training/testing sets
#random_state is so that the output is always the same. 42 seems to be the norm to use
# stratify = y "to split y values evenly"
# Using skelearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                                    test_size=0.2, 
                                                    random_state=42, 
                                                    stratify = y)

In [15]:
dclf = DummyClassifier()

dclf.fit(X_train,y_train)

y_pred_dclf = dclf.predict(X_test)

C:\Users\reaso\anaconda3\lib\site-packages\sklearn\dummy.py:131: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  warnings.warn("The default value of strategy will change from "


In [16]:
f1_score(y_test, y_pred_dclf, average = None)

array([0.55489022, 0.4626506 ])

In [17]:
con_matrix = confusion_matrix(y_test,y_pred_dclf)
con_matrix

array([[139, 112],
       [111,  96]], dtype=int64)

In [18]:
# LogisticRegression model

logreg = LogisticRegression()

# Fit train dataset

logreg.fit(X_train,y_train.values.ravel())

# Store predictions with model using X test data

y_logreg_pred = logreg.predict(X_test)

In [19]:
# F1 score of logisticRegression Model
f'F1 Score: {f1_score(y_test,y_logreg_pred,average = None)}'

'F1 Score: [0.89179104 0.84736842]'

In [20]:
# Confusion Matrix score of logisticRegression Model
con_mat= confusion_matrix(y_test,y_logreg_pred)
con_mat

array([[239,  12],
       [ 46, 161]], dtype=int64)

In [21]:
# Accuracy Metric
f'Accuracy: {metrics.accuracy_score(y_test,y_logreg_pred)}'

'Accuracy: 0.8733624454148472'

In [22]:
# Train a DecisionTreeClassifer model

tclf = DecisionTreeClassifier()

# Fit dataset

tclf.fit(X_train,y_train.values.ravel())

# predict results

y_tclf_pred = tclf.predict(X_test)

In [23]:
# F1 score of DecisionTreeClassifier

f'F1 Score: {f1_score(y_test,y_tclf_pred,average = None)}'

'F1 Score: [0.85360825 0.83526682]'

In [24]:
# Confusion Matrix score of DecisionTreeClassifier Model

tclf_con_mat= confusion_matrix(y_test,y_tclf_pred)
tclf_con_mat

array([[207,  44],
       [ 27, 180]], dtype=int64)

In [25]:
# Accuracy Metric
f'Accuracy: {metrics.accuracy_score(y_test,y_tclf_pred)}'

'Accuracy: 0.8449781659388647'

In [26]:
# Train RandomForestClassifer model

rclf = RandomForestClassifier()

# Fit dataset

rclf.fit(X_train,y_train.values.ravel())

# predict results

y_rclf_pred= rclf.predict(X_test)

In [27]:
# F1 score of RandomTreeClassifier

f'F1 Score: {f1_score(y_test,y_rclf_pred,average = None)}'

'F1 Score: [0.9017341  0.87153652]'

In [28]:
# Confusion Matrix score of RandomForestClassifier Model

rclf_con_mat= confusion_matrix(y_test,y_rclf_pred)
rclf_con_mat

array([[234,  17],
       [ 34, 173]], dtype=int64)

In [29]:
# Accuracy Metric
f'Accuracy: {metrics.accuracy_score(y_test,y_rclf_pred)}'

'Accuracy: 0.888646288209607'

In [30]:
#Create a DataFrame containing the sorted feature importances of the RandomTreeClassifier

importances = list(zip(df_vect.columns, rclf.feature_importances_))

#Create DataFrame with above list

df_test = pd.DataFrame(importances)

#rename column in DataFrame

df_test.rename(columns ={0:'feature', 1:'importances'}, inplace = True)

# sort DataFrame by importances

df_test.sort_values(by=['importances'], ascending = False).style.hide_index()


In [31]:
#Test a few strings and see if they are misogynist
#
# Statements taken from: https://www.huffpost.com/entry/common-misogyny-phrases-women_n_6108750ee4b0497e67027549
#

statement_1 = 'That outfit she’s wearing is asking for it.'
statement_2 = 'Does your spouse know you are hanging out with your friends/cutting your hair so short/making plans whatsoever'
statement_3 = 'You look prettier when you smile!'
statement_4 = 'You’re not like other girls'
statement_5 = 'If you’re trans, you need to act like a woman'
statement_6 = 'You’re too emotional'

#Append the strings into a list
test_list = []
test_list.append(statement_1)
test_list.append(statement_2)
test_list.append(statement_3)
test_list.append(statement_4)
test_list.append(statement_5)
test_list.append(statement_6)



In [50]:

vectorizer = vectorizer.fit_transform(test_list)

In [51]:
df_test_list = pd.DataFrame.sparse.from_spmatrix(vectorizer)


In [54]:
y_rclf_pred= rclf.predict(df_test_list)

ValueError: Number of features of the model must match the input. Model n_features is 950 and input n_features is 42 